import type { User, Bet, UserBet } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Johnson",
    handle: "alicej",
    avatar: "/woman-profile-photo.png",
    balance: { USD: 1500, KES: 150000, NGN: 650000 },
  },
  {
    id: "user-2",
    name: "Bob Smith",
    handle: "bobsmith",
    avatar: "/man-profile.png",
    balance: { USD: 2500, KES: 250000, NGN: 1050000 },
  },
  {
    id: "user-3",
    name: "Charlie Brown",
    handle: "charlieb",
    avatar: "/man-profile.png",
    balance: { USD: 800, KES: 80000, NGN: 340000 },
  },
  {
    id: "user-4",
    name: "Diana Prince",
    handle: "dprince",
    avatar: "/woman-profile-photo.png",
    balance: { USD: 3200, KES: 320000, NGN: 1350000 },
  },
  {
    id: "user-5",
    name: "Ethan Hunt",
    handle: "ehunt",
    avatar: "/man-profile.png",
    balance: { USD: 1200, KES: 120000, NGN: 510000 },
  },
  {
    id: "user-6",
    name: "Fiona Green",
    handle: "fionagreen",
    avatar: "/woman-profile-photo.png",
    balance: { USD: 1800, KES: 180000, NGN: 760000 },
  },
]

export const mockBets: Bet[] = [
  {
    id: "bet-1",
    title: "Will Bitcoin reach $100k by end of 2025?",
    description: "Resolves YES if Bitcoin price reaches $100,000 USD on any major exchange",
    creator: { id: "creator-1", name: "Alex Crypto", handle: "alexcrypto", avatar: "/crypto-trader-profile-photo.jpg" },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 7 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 40 * 86400000).toISOString(),
    yesBets: [{ userId: "user-1" }, { userId: "user-2" }, { userId: "user-5" }],
    noBets: [{ userId: "user-3" }, { userId: "user-4" }],
    createdAt: new Date().toISOString(),
  },
  {
    id: "bet-2",
    title: "Will Taylor Swift win a Grammy in 2025?",
    description: "Resolves YES if Taylor Swift wins any Grammy award in 2025",
    creator: { id: "creator-2", name: "Music Fan", handle: "musicfan", avatar: "/music-enthusiast-profile.jpg" },
    image: "/music-award-stage-with-spotlights.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 5 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 35 * 86400000).toISOString(),
    yesBets: [{ userId: "user-1" }, { userId: "user-3" }, { userId: "user-6" }, { userId: "user-2" }],
    noBets: [{ userId: "user-4" }],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "bet-3",
    title: "Will SpaceX land humans on Mars by 2030?",
    description: "Resolves YES if humans successfully land on Mars and return safely",
    creator: { id: "creator-3", name: "Space Nerd", handle: "spacenerd", avatar: "/space-enthusiast-astronomer.jpg" },
    image: "/mars-landing-spacecraft.jpg",
    currency: "KES",
    bettingEndsAt: new Date(Date.now() + 10 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 45 * 86400000).toISOString(),
    yesBets: [{ userId: "user-5" }],
    noBets: [
      { userId: "user-1" },
      { userId: "user-2" },
      { userId: "user-3" },
      { userId: "user-4" },
      { userId: "user-6" },
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "bet-4",
    title: "Will Apple release Vision Pro 2 in 2025?",
    description: "Resolves YES if Apple announces or releases Vision Pro Gen 2",
    creator: { id: "creator-4", name: "Tech Insider", handle: "techinsider", avatar: "/tech-expert-portrait.jpg" },
    image: "/futuristic-vr-headset-technology.jpg",
    currency: "NGN",
    bettingEndsAt: new Date(Date.now() + 6 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    yesBets: [{ userId: "user-2" }, { userId: "user-6" }],
    noBets: [{ userId: "user-3" }, { userId: "user-4" }, { userId: "user-5" }],
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "bet-5",
    title: "Will Ethereum reach $5,000 by Q2 2025?",
    description: "Resolves YES if ETH price hits $5,000 on any major exchange",
    creator: {
      id: "user-1",
      name: "Your Name",
      handle: "yourhandle",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "USD",
    bettingEndsAt: new Date(Date.now() + 14 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 60 * 86400000).toISOString(),
    yesBets: [{ userId: "user-2" }, { userId: "user-5" }],
    noBets: [{ userId: "user-3" }],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    resolved: false,
  },
  {
    id: "bet-6",
    title: "Will Arsenal win the Premier League 2025?",
    description: "Resolves YES if Arsenal wins the Premier League championship",
    creator: {
      id: "user-1",
      name: "Your Name",
      handle: "yourhandle",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/mars-landing-spacecraft.jpg",
    currency: "KES",
    bettingEndsAt: new Date(Date.now() + 21 * 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 90 * 86400000).toISOString(),
    yesBets: [{ userId: "user-1" }, { userId: "user-4" }, { userId: "user-6" }],
    noBets: [{ userId: "user-2" }, { userId: "user-5" }],
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    resolved: false,
  },
  {
    id: "bet-7",
    title: "Will Bitcoin crash below $50k in 2025?",
    description: "Resolves YES if BTC falls below $50,000",
    creator: {
      id: "user-1",
      name: "Your Name",
      handle: "yourhandle",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user1",
    },
    image: "/bitcoin-chart-with-growth-trend.jpg",
    currency: "NGN",
    bettingEndsAt: new Date(Date.now() - 86400000).toISOString(),
    resolutionDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    yesBets: [{ userId: "user-3" }],
    noBets: [{ userId: "user-2" }, { userId: "user-4" }, { userId: "user-5" }, { userId: "user-6" }],
    createdAt: new Date(Date.now() - 864000000).toISOString(),
    resolved: true,
    resolution: "no",
  },
]

export const mockUserBets: UserBet[] = [
  {
    betId: "bet-1",
    userId: "current-user",
    prediction: "yes",
    amount: 50,
    placedAt: new Date(Date.now() - 86400000).toISOString(),
    resolved: false,
    won: undefined,
  },
  {
    betId: "bet-2",
    userId: "current-user",
    prediction: "yes",
    amount: 100,
    placedAt: new Date(Date.now() - 172800000).toISOString(),
    resolved: true,
    won: true,
  },
  {
    betId: "bet-3",
    userId: "current-user",
    prediction: "no",
    amount: 75,
    placedAt: new Date(Date.now() - 259200000).toISOString(),
    resolved: true,
    won: true,
  },
]

export const mockCreatedBets: Bet[] = mockBets.filter((bet) => bet.creator.id === "user-1")
